
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 05 09:23:44 CST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 2;
  public static final int Output = 24;
  public static final int Begin = 9;
  public static final int End = 10;
  public static final int Until = 21;
  public static final int Coma = 5;
  public static final int Op_booleano = 23;
  public static final int Repeat = 14;
  public static final int If = 12;
  public static final int T_datoS = 15;
  public static final int Var = 22;
  public static final int T_datoN = 16;
  public static final int Else = 11;
  public static final int Asignacion = 3;
  public static final int Then = 18;
  public static final int T_datoB = 17;
  public static final int While = 19;
  public static final int Division = 28;
  public static final int Cadena = 33;
  public static final int Parentesis_c = 32;
  public static final int Parentesis_a = 31;
  public static final int EOF = 0;
  public static final int P_coma = 30;
  public static final int error = 1;
  public static final int ERROR = 35;
  public static final int Do = 20;
  public static final int Op_logico = 4;
  public static final int Identificador = 6;
  public static final int Input = 13;
  public static final int Resta = 25;
  public static final int Multiplicacion = 27;
  public static final int Op_incremento = 34;
  public static final int Numero = 7;
  public static final int Program = 8;
  public static final int Suma = 26;
  public static final int Igual = 29;
}

